### ISSUE TITLE
Adding new logo in clients 

### ISSUE THREAD

**Issue by DiviyamPathak** [iamsuprava/Bharath.Web#1]
I will Import logos from assets in clients state in the state store and rebuild application which in turn will add new logos in page

**Comment by DiviyamPathak** [comment]
Will be done @11 pm nov

**Comment by iamsuprava** [comment]
Okay

**Comment by DiviyamPathak** [comment]
there seems to be problem with importing new logos it shld be imported with new way ex import Hyundailogo from '../assets/Hyundailogo.png'
rather then all of them together I think its because of vite does not allow non configured asstes
